=== divljiboy/XMLProjekat/XML-Projekat/src/main/schema/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="aktovi" xmlns:akt="aktovi">
    <xs:element name="Pravni_akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Preambula" type="xs:string"/>
                <xs:element name="Naziv" type="xs:string"/>
                <xs:element ref="akt:Glavni_deo"/>
                <xs:element name="Drzava" type="xs:string"/>
                <xs:element name="Pokrajina" type="xs:string"/>
                <xs:element name="Grad" type="xs:string"/>
                <xs:element name="Skupstina" type="xs:string"/>
                <xs:element name="Broj_popisa_kod_organa" type="xs:string"/>
                <xs:element name="Datum_donosenja_propisa" type="xs:string"/>
                <xs:element name="Mesto_donosenja_propisa" type="xs:string"/>
                <xs:element name="Ovlasceno_lice" type="akt:TOvlasceno_lice"/>
            </xs:sequence>
            <xs:attribute name="Usvojen" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:choice>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Glava"/>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="akt:Odeljak"/>
                <xs:element maxOccurs="unbounded" ref="akt:Clan"/>
            </xs:choice>
            <xs:attribute name="Redni_broj" type="xs:string"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:choice>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="akt:Odeljak"/>
                <xs:element maxOccurs="unbounded" ref="akt:Clan"/>
            </xs:choice>
            <xs:attribute name="Naziv" type="akt:TGlava_naziv"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="akt:Odeljak"/>
                <xs:element maxOccurs="unbounded" ref="akt:Clan"/>
            </xs:choice>
            <xs:attribute name="Naziv" type="akt:TOdeljak_naziv"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element maxOccurs="unbounded" ref="akt:Stav"/>
            </xs:choice>
            <xs:attribute name="Broj_clana" type="xs:integer" use="required"/>
            <xs:attribute name="Naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Tacka"/>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Alineja"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Tacka">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Podtacka"/>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Alineja"/>
            </xs:choice>
            <xs:attribute name="broj" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podtacka">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="akt:Alineja"/>
            </xs:choice>
            <xs:attribute name="broj" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alineja" type="xs:string"/>
    <xs:simpleType name="TOdeljak_naziv">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9][0-9]*\. .*"/>
            <xs:pattern value="[A-Z]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TGlava_naziv">
        <xs:restriction base="xs:string">
            <xs:pattern value="Glava \p{N}"/>
            <xs:pattern value="\p{N}\. .*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="Glavni_deo">
        <xs:complexType mixed="false">
            <xs:choice maxOccurs="1" minOccurs="1">
                <xs:element maxOccurs="unbounded" ref="akt:Deo"/>
                <xs:element maxOccurs="unbounded" ref="akt:Glava"/>
                <xs:element maxOccurs="unbounded" ref="akt:Odeljak"/>
                <xs:element maxOccurs="unbounded" ref="akt:Clan"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOdbornik">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element name="Uloga" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPredsednik_skupstine">
        <xs:complexContent>
            <xs:extension base="akt:TOdbornik">
                <xs:sequence>
                    <xs:element name="Plata" type="xs:decimal"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TOvlasceno_lice">
        <xs:sequence>
            <xs:element name="Titula" type="xs:string"/>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TKorisnik">
        <xs:sequence>
            <xs:element name="Username" type="xs:string"/>
            <xs:element name="Password" type="xs:string"/>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element name="Uloga" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Korisnik" type="akt:TKorisnik"/>
</xs:schema>

=== divljiboy/XMLProjekat/XML-Projekat/src/main/schema/examples/Zakon o zastiti zemljista.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pravni_akt xmlns="aktovi"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="aktovi file:/C:/Users/Dorian/Desktop/Faks/Cetvrta_godina/XML%20i%20Web%20servisi/git_proj/XMLProjekat/XML-Projekat/src/main/schema/akt.xsd">
    <Stanje></Stanje>
    <Naziv>Z A K O N
        O ZAŠTITI ZEMLjIŠTA</Naziv>
    <Glavni_deo>
        
        <Glava Id="1" Naziv="OSNOVNE ODREDBE">
            
            <Clan Broj_clana="1">
                <Stav Id="1">
                    Ovim zakonom uređuje se zaštita zemljišta, sistematsko praćenje
                    stanja i kvaliteta zemljišta, mere sanacije, remedijacije, rekultivacije,
                    inspekcijski nadzor i druga pitanja od značaja za zaštitu i očuvanje
                    zemljišta kao prirodnog resursa od nacionalnog interesa.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="2">
                <Stav Id="1">
                    Odredbe ovog zakona primenjuju se na sve tipove zemljišta Republike
                    Srbije kao prirodni resurs, bez obzira na oblik svojine, njegovu namenu i
                    korišćenje.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="3">
                <Stav Id="1">
                    Cilj ovog zakona je da se očuvaju površine i funkcije zemljišta kao
                    prirodnog resursa i da se spreče ili otklone štetne promene u zemljištu
                    koje mogu da nastanu kao posledica:
                    <Tacka broj="1">erozionih procesa;</Tacka>
                    <Tacka broj="2">smanjenja sadržaja organske materije u zemljištu;</Tacka>
                    <Tacka broj="3">neprimerene poljoprivredne i šumske proizvodnje (neadekvatne i
                        nekontrolisane agrotehničke i meliorativne mere, krčenje šuma i dr);</Tacka>
                    <Tacka broj="4">nekontrolisane promene namene, upravljanja i korišćenja
                        zemljišta;</Tacka>
                    <Tacka broj="5">neplanske urbanizacije, odnosno izgradnje i razvoja
                        infrastrukture;</Tacka>
                    <Tacka broj="6">zakiseljavanja (acidifikacija), zaslanjivanja (salinizacija) i
                        alkalizacije zemljišta;</Tacka>
                </Stav>
            </Clan>
            
            <Clan Broj_clana="4" Naziv="Značenje izraza">
                <Stav Id="1">
                    Izrazi upotrebljeni u ovom zakonu imaju sledeće značenje:
                    <Tacka broj="1">aktivnost koja utiče na zemljište jeste svaki privremeni,
                        povremeni ili stalni zahvat kojim se menja ili se može promeniti stanje i
                        uslovi na nekoj lokaciji;</Tacka>
                    <Tacka broj="2">
                        granične vrednosti jesu vrednosti zagađujućih, štetnih i opasnih
                        materija u zemljištu koje mogu biti:
                        <Podtacka broj="1">granična minimalna vrednost jeste vrednost zagađujućih,
                            štetnih i opasnih materija u zemljištu koja se bazira na njihovom prirodnom
                            sadržaju i predstavlja vrednost za nezagađeno zemljište, pri čemu nije ili je
                            minimalno narušena ekološka ravnoteža;</Podtacka>
                        <Podtacka broj="2">granična maksimalna vrednost jeste vrednost zagađujućih,
                            štetnih i opasnih materija u zemljištu čije prekoračenje ukazuje na nivo
                            kontaminacije koji narušava ekološku ravnotežu, nameće dodatna ispitivanja
                            tog zemljišta kao i ograničenja u načinu upravljanja;</Podtacka>
                    </Tacka>
                    <Tacka broj="3">degradacija zemljišta jeste proces narušavanja kvaliteta i
                        funkcija zemljišta koji nastaje prirodnim putem ili ljudskom aktivnošću
                        ili je posledica nepreduzimanja mera za sprečavanje štetnih posledica;</Tacka>
                    <Tacka broj="4">dobra stručna praksa predstavlja primenu naučnih, tehničkih i
                        biotehničkih mera i/ili mera upravljanja i korišćenja zemljišta u cilju
                        očuvanja i unapređivanja kvaliteta zemljišta;</Tacka>
                    <Tacka broj="5">državna mreža predstavlja prostorno pozicionirana merna mesta
                        uzorkovanja zemljišta za potrebe državnog monitoringa;</Tacka>
                </Stav>
            </Clan>
            
        </Glava>
        <Glava Id="2" Naziv="PROGRAM SISTEMATSKOG PRAĆENjA STANjA I
            KVALITETA ZEMLjIŠTA">
            
            <Clan Broj_clana="5">
                <Stav Id="1">
                    Republika, autonomna pokrajina i jedinice lokalne samouprave, u
                    okviru svojih nadležnosti utvrđenih zakonom, obezbeđuju sistematsko
                    praćenje stanja i kvaliteta zemljišta (u daljem tekstu: monitoring
                    zemljišta) i održavanje baze podataka o stanju i kvalitetu zemljišta, u
                    skladu sa Programom monitoringa zemljišta.
                </Stav>
                <Stav Id="2">Vlada utvrđuje sadržinu Programa monitoringa zemljišta,
                    metodologiju za sistematsko praćenje kvaliteta i stanja zemljišta,
                    kriterijume za određivanje broja i rasporeda mernih mesta, listu parametara
                    za određeni tip zemljišta, listu metoda i standarda koji se koriste za
                    uzorkovanje zemljišta, analizu uzoraka i obradu podataka, obim i učestalost
                    merenja, indikatore za ocenu rizika od degradacije zemljišta, rokove i način
                    dostavljanja podataka.</Stav>
            </Clan>
            <Clan Broj_clana="6">
                <Stav Id="1">
                    Po zakonu <Referenca ref_akt="1">akta 1.</Referenca> vlasnik zemljišta, zakupac ili korisnik zemljišta, dužan je da
                    omogući ovlašćenom pravnom licu uzimanje uzoraka za potrebe obavljanja
                    monitoringa zemljišta.
                </Stav>
            </Clan>
            
        </Glava>
        
    </Glavni_deo>
    <Drzava>Republika Srbija</Drzava>
    <Pokrajina>Autonomna pokrajina Vojvodina</Pokrajina>
    <Grad>Grad Novi Sad</Grad>
    <Skupstina>Skupstina grada Novog Sada</Skupstina>
    <Broj_popisa_kod_organa>34643412465677</Broj_popisa_kod_organa>
    <Datum_donosenja_propisa>17.06.2016</Datum_donosenja_propisa>
    <Mesto_donosenja_propisa>Novi Sad</Mesto_donosenja_propisa>
    <Ovlasceno_lice>
        <Titula>Odbornik</Titula>
        <Ime>Goran</Ime>
        <Prezime>Cogic</Prezime>
    </Ovlasceno_lice>
    <Timestamp>2002-05-30T09:00:00</Timestamp>
</Pravni_akt>

=== divljiboy/XMLProjekat/XML-Projekat/src/main/schema/zaelera1.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt:Pravni_akt xmlns:akt="aktovi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="aktovi file:/C:/Users/Dorian/Desktop/Faks/Cetvrta_godina/XML%20i%20Web%20servisi/git_proj/XMLProjekat/XML-Projekat/src/main/schema/akt.xsd"
    Id="9"
    >
    <akt:Stanje>Stanje0</akt:Stanje>
    <akt:Naziv>Naziv 9</akt:Naziv>
    <akt:Glavni_deo>
        <akt:Glava Id="1" Naziv="Glava 1">
            <akt:Odeljak Id="1" Naziv="Odeljak 1">
                <akt:Clan Broj_clana="1">
                    <akt:Stav>Znaci kidamo</akt:Stav>
                    <akt:Stav>xml</akt:Stav>
                </akt:Clan>
                <akt:Clan Broj_clana="2">
                    <akt:Stav>Najjaci smo</akt:Stav>
                    <akt:Stav>breee</akt:Stav>
                </akt:Clan>
            </akt:Odeljak>
            <akt:Odeljak>
                <akt:Clan Broj_clana="3">
                    <akt:Stav>Ala cemo da trsnemo gzemel</akt:Stav>
                    <akt:Stav>Nista nismo uradili</akt:Stav>
                </akt:Clan>
                <akt:Clan Broj_clana="4">
                    <akt:Stav>Belgija 0:1 Italija</akt:Stav>
                    <akt:Stav>Belgija osvaja</akt:Stav>
                </akt:Clan>
            </akt:Odeljak>
        </akt:Glava>
        <akt:Glava Id="2" Naziv="Glava 2">
            <akt:Clan Broj_clana="5">
                <akt:Stav>Opa ima i druga glava</akt:Stav>
                <akt:Stav>Ali ova nema odeljak</akt:Stav>
            </akt:Clan>
            <akt:Clan Broj_clana="6">
                <akt:Stav>Znaci zaos</akt:Stav>
                <akt:Stav>Cogara najjaci na raftingu</akt:Stav>
            </akt:Clan>
        </akt:Glava>
    </akt:Glavni_deo>
    <akt:Drzava>Ruthenia</akt:Drzava>
    <akt:Pokrajina>Vojvodina</akt:Pokrajina>
    <akt:Grad>Ruski Krstur</akt:Grad>
    <akt:Skupstina>Nemamo</akt:Skupstina>
    <akt:Broj_popisa_kod_organa>12345</akt:Broj_popisa_kod_organa>
    <akt:Datum_donosenja_propisa>21.01.2015</akt:Datum_donosenja_propisa>
    <akt:Mesto_donosenja_propisa>Ruski Krstur</akt:Mesto_donosenja_propisa>
    <akt:Ovlasceno_lice>
        <akt:Titula>Predsednik</akt:Titula>
        <akt:Ime>Dorian</akt:Ime>
        <akt:Prezime>Cizmar</akt:Prezime>
    </akt:Ovlasceno_lice>
</akt:Pravni_akt>

=== divljiboy/XMLProjekat/XML-Projekat/src/main/schema/examples/Zakon o policiji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pravni_akt xmlns="aktovi"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="aktovi file:/C:/Users/Dorian/Desktop/Faks/Cetvrta_godina/XML%20i%20Web%20servisi/git_proj/XMLProjekat/XML-Projekat/src/main/schema/akt.xsd">
    <Stanje></Stanje>
    <Naziv>Z A K O N
        O POLICIJI</Naziv>
    <Glavni_deo>
        
        <Glava Id="1" Naziv="OSNOVNE ODREDBE">
            
            <Clan Broj_clana="1" Naziv="Predmet zakona">
                <Stav Id="1" >
                    Ovim zakonom uređuju se unutrašnji poslovi, organizacija i
                    nadležnost Ministarstva unutrašnjih poslova (u daljem tekstu:
                    Ministarstvo), policijski poslovi, organizacija i nadležnost Policije, kao i
                    druga pitanja od značaja za rad Policije i Ministarstva.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="2" Naziv="Pojam unutrašnjih poslova">
                <Stav Id="1">
                    Unutrašnji poslovi su zakonom utvrđeni poslovi državne uprave, koje
                    obavlja Ministarstvo, a čijim obavljanjem se ostvaruje i unapređuje
                    bezbednost građana i imovine, pruža podrška vladavini prava i obezbeđuje
                    ostvarivanje Ustavom i zakonom utvrđenih ljudskih i manjinskih prava i
                    sloboda, kao i drugi, sa njima povezani poslovi iz utvrđenog delokruga i
                    nadležnosti Ministarstva.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="3" Naziv="Policija">
                <Stav Id="1">
                    Policija je centralna organizaciona jedinica Ministarstva koja u
                    obavljanju unutrašnjih odnosno policijskih poslova, štiti i unapređuje
                    bezbednost građana i imovine, poštujući Ustavom zajemčena ljudska i
                    manjinska prava i slobode i druge zaštićene vrednosti u demokratskom
                    društvu, uz mogućnost na Ustavu i zakonu zasnovane upotrebe sredstava
                    prinude.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="4">
                <Stav Id="1">
                    Ministar unutrašnjih poslova (u daljem tekstu: ministar) u okviru
                    odredbi ovog zakona, propisuje način obavljanja unutrašnjih poslova.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="5" Naziv="Informisanje o radu Ministarstva">
                <Stav Id="1">Rad Ministarstva je javan.</Stav>
                <Stav Id="2">
                    Ministarstvo redovno blagovremeno i potpuno obaveštava javnost o
                    svom radu, osim u slučajevima preduzimanja mera i radnji u skladu sa zakonom
                    kojim se uređuje krivični postupak i kada bi to onemogućilo neometan
                    operativni rad Policije, ili ako bi se time:
                    <Tacka broj="1">povredio propis o tajnosti podataka;</Tacka>
                    <Tacka broj="2">povredilo dostojanstvo građana;</Tacka>
                    <Tacka broj="3">ugrozilo pravo na ličnu slobodu i bezbednost.</Tacka>
                </Stav>
                <Stav Id="3">
                    Ministarstvo jednom godišnje, a najkasnije u roku od tri meseca od
                    završetka kalendarske godine, objavljuje:
                    <Tacka broj="1">
                        izveštaj o stanju bezbednosti u Republici Srbiji koji na
                        transparentan i javan način obaveštava javnost o proceni bezbednosti,
                        trendovima kretanja kriminala i drugih bezbednosnih pojava od značaja za
                        bezbednost i prava građana;
                    </Tacka>
                    <Tacka broj="2">
                        izveštaj o radu Ministarstva, koji na transparentan i javan način
                        obaveštava javnost o razvoju policije, statističkim podacima o sprovedenim
                        aktivnostima i postignutim rezultatima.
                    </Tacka>
                    
                    Pored izveštaja iz <Referenca ref_stav="3">stava 3.</Referenca> ovog člana, Ministarstvo je u obavezi da
                    objavi na svojoj internet prezentaciji i tromesečne informacije o radu, koje
                    usvaja nadležni odbor Narodne skupštine Republike Srbije za unutrašnje
                    poslove.
                </Stav>
            </Clan>
            
        </Glava>
        
        <Glava Id="2" Naziv="SARADNjA MINISTARSTVA">
            
            <Clan Broj_clana="6" Naziv="Saradnja sa službama bezbednosti">
                <Stav Id="1">
                    Ministarstvo neposredno sarađuje sa službama bezbednosti u
                    Republici Srbiji kroz razmenu informacija i tehničku saradnju, u skladu sa
                    zakonom.
                </Stav>
                <Stav Id="2">
                    Saradnja iz <Referenca ref_clan="3" ref_stav="1">stava 1. člana 3.</Referenca> zasniva se na pravima i dužnostima
                    utvrđenim Ustavom, zakonom, drugim propisima i opštim aktima i na
                    posebnim oblicima organizovanja i uzajamnog obaveštavanja u izvršavanju
                    zajedničkih zadataka.
                </Stav>
            </Clan>
            
            <Clan Broj_clana="7">
                <Stav Id="1">
                    Organizacione jedinice u sedištu Direkcije policije, Policijska
                    uprava za Grad Beograd i policijske uprave obrazuju se tako da su radno i
                    funkcionalno povezane sa odgovarajućim organizacionim jedinicama i
                    poslovima na način da srodne policijske poslove iz svog delokruga obavljaju
                    na centralnom, regionalnom i lokalnom nivou.
                </Stav>
                <Stav Id="2">
                    Direkcijom policije rukovodi direktor policije.
                </Stav>
                <Stav Id="3">
                    Rukovođenje i odgovornost u Direkciji policije zasniva se na načelu
                    jednostarešinstva i subordinacije.
                </Stav>
                <Stav Id="4">
                    Specijalna i posebne jedinice policije angažuju se odlukom
                    rukovodioca odgovarajuće organizacione jedinice.
                </Stav>
                <Stav Id="5">
                    Za angažovanje Žandarmerije, rukovodilac organizacione jedinice
                    pribavlja prethodno odobrenje direktora policije.
                </Stav>
                <Stav Id="6">
                    Izuzetno od <Referenca ref_stav="1" ref_clan="3">st. 1 člana 3.</Referenca>, Specijalna antiteroristička
                    jedinica, Helikopterska jedinica i Žandarmerija prilikom angažovanja koje
                    obuhvata upotrebu jednog ili više odreda u maksimalnom kapacitetu, angažuju
                    se odlukom rukovodioca odgovarajuće organizacione jedinice uz prethodno
                    pribavljeno odobrenje direktora policije i prethodno pribavljenu
                    saglasnost ministra.
                </Stav>
            </Clan>
            
        </Glava>
        
    </Glavni_deo>
    <Drzava>Republika Srbija</Drzava>
    <Pokrajina>Autonomna pokrajina Vojvodina</Pokrajina>
    <Grad>Grad Novi Sad</Grad>
    <Skupstina>Skupstina grada Novog Sada</Skupstina>
    <Broj_popisa_kod_organa>6541282168421554</Broj_popisa_kod_organa>
    <Datum_donosenja_propisa>17.06.2016</Datum_donosenja_propisa>
    <Mesto_donosenja_propisa>Novi Sad</Mesto_donosenja_propisa>
    <Ovlasceno_lice>
        <Titula>Predsednik</Titula>
        <Ime>Zoran</Ime>
        <Prezime>Cogic</Prezime>
    </Ovlasceno_lice>
    <Timestamp>2002-05-30T09:00:00</Timestamp>
</Pravni_akt>

=== divljiboy/XMLProjekat/XML-Projekat/src/main/schema/temp/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt:Pravni_akt xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
 xmlns:akt="aktovi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="aktovi file:/C:/Users/Dorian/Desktop/Faks/Cetvrta_godina/XML%20i%20Web%20servisi/git_proj/XMLProjekat/XML-Projekat/src/main/schema/temp/akt.xsd">
    <akt:Stanje>Stanje0</akt:Stanje>
    <akt:Naziv>Naziv0</akt:Naziv>
    <akt:Glavni_deo>
        <akt:Deo>
            <akt:Odeljak>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
            </akt:Odeljak>
            <akt:Odeljak>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
            </akt:Odeljak>
        </akt:Deo>
        <akt:Deo>
            <akt:Odeljak>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
            </akt:Odeljak>
            <akt:Odeljak>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
                <akt:Clan Broj_clana="50">
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                    <akt:Stav/>
                </akt:Clan>
            </akt:Odeljak>
        </akt:Deo>
    </akt:Glavni_deo>
    <akt:Drzava>Drzava0</akt:Drzava>
    <akt:Pokrajina>Pokrajina0</akt:Pokrajina>
    <akt:Grad>Grad0</akt:Grad>
    <akt:Skupstina>Skupstina0</akt:Skupstina>
    <akt:Broj_popisa_kod_organa>Broj_popisa_kod_organa0</akt:Broj_popisa_kod_organa>
    <akt:Datum_donosenja_propisa>Datum_donosenja_propisa0</akt:Datum_donosenja_propisa>
    <akt:Mesto_donosenja_propisa>Mesto_donosenja_propisa0</akt:Mesto_donosenja_propisa>
    <akt:Ovlasceno_lice>
        <akt:Titula>Titula0</akt:Titula>
        <akt:Ime>Ime0</akt:Ime>
        <akt:Prezime>Prezime0</akt:Prezime>
    </akt:Ovlasceno_lice>
    <akt:Timestamp>2006-05-04T18:13:51.0</akt:Timestamp>
</akt:Pravni_akt>
